export class DeviceInfoBean {

  // "shareable": 1,
  // "ownerStatus": 1,
  // "gid": "tggbwi",
  // "deviceCookie": null,
  // "icon": "https://iot-test.wasumedia.cn/file/group1/M00/00/01/fdKjil1Lg9SAWNArAABGVnll_8k545.png",
  // "deviceId": "03034A8897C5259F98EBD",
  // "deviceName": "机顶盒",
  // "displayAttribute": [],
  // "firm": "TIM",
  // "bindTime": "2023-08-04 16:04:42",
  // "deviceUid": "d61f85e39b4d44aaa2c2afd7afc19d8e",
  // "model": "FGH",
  // "thirdCloudId": 38,
  // "tpid": null,
  // "productId": "053",
  // "display": true,
  // "modelType": 6,
  // "resVer": "1.0.0",
  // "roomName": "卫生间",
  // "productCode": "stb",
  // "virtDeviceUid": "31973b7599df8d6c55a7dc306b1f134b",
  // "shareExpire": null,
  // "isShare": false,
  // "online": 1,
  // "gatewayId": null


  shareable: number
  ownerStatus: number
  gid: string
  icon: string
  deviceId: string
  deviceName: string
  bindTime: string
  deviceUid: string
  model: string
  thirdCloudId: number
  productId: string
  display: boolean
  modelType: number
  roomName: string
  productCode: string
  virtDeviceUid: string
  isShare: boolean
  online: number
  gatewayId: string
}